name: communication_channels
description: This package is used to make the communication process between isolates(services) more maintainable and systematic.
version: 1.0.0
repository: https://github.com/BolaAshEf/communication_channels

environment:
  sdk: ^3.1.0

dependencies:
  easy_serialization: ^1.0.1
  equatable: ^2.0.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
